### ISSUE TITLE
[tests]: schemas with type array must declare items subschema

### ISSUE THREAD

**Issue by MikeRalphson** [kevinswiber/postman2openapi#6]
A wrinkle in 3.0 which will be going away in 3.1

> items - Value MUST be an object and not an array. Inline or referenced schema MUST be of a Schema Object and not a standard JSON Schema. items MUST be present if the type is array.

The empty schema `{}` is sufficient, e.g.:

```yaml
randomSchemaOrSubSchema:
   type: array
   items: {}
```

Shows up in `echo` fixture and others.
